# mayor que
print(7 > 3)
print(3 > 7)
print(7 > 7)
# menor que
print(5 < 6)
print(6 < 5)
print(5 < 5)
# mayor o igual que
print(2 >= 1)
print(2 >= 3)
print(2 >= 2)
# menor o igual que
print(1 <= 2)
print(2 <= 1)
print(2 <= 2)
# igual que
print(6 == 6)
print(5 == 2)
# diferente que
print(6 != 10)
print(6 != 6)
# comparar strings
print("Apple" == 'Apple')
print("Apple" == 'apple')
print("1" == 1)
# comparar variables
age = 15
print(age >= 18)
