#not
print('NOT')
print('not True =>', not True)
print('not False =>', not False)
print('not True and True =>', not (True and True))
print('not True and False =>', not (True and False))
print('not False and True =>', not (False and True))
print('not False and False =>', not (False and False))
print('not True or True =>', not (True or True))
print('not True or False =>', not (True or False))
print('not False or True =>', not (False or True))
print('not False or False =>', not (False or False))